spring:
    application:
        name: work
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://39.107.229.253:3306/jadepearl_app?useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 114514
server:
    port: 8004
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
feign:
    hystrix:
        enabled: true